### ISSUE TITLE
Messages should close after a period of time.

### ISSUE THREAD

**Issue by apfunk** [idoco/map-chat#16]
The map gets extremely cluttered. It would help if the messages closed automatically after a set amount of time.

**Comment by alfonsomga** [comment]
:+1:

**Comment by Rockdtben** [comment]
PR: #11 
Issue: #6

**Comment by idoco** [comment]
This was implemented in [this commit](https://github.com/idoco/map-chat/commit/31d3ea18b94a520d894e8b2a6326ae00fc061f86) with a hard-coded 10 seconds time out. we can improve this in the future. 
Thanks!
