### ISSUE TITLE
Sanitize chat messages more effectively

### ISSUE THREAD

**Issue by jamesa** [idoco/map-chat#2]
Saw some nefarious things going on, namely iframes, arbitrary javascript execution, redirects, HTML in messages.

**Comment by idoco** [comment]
Thanks for the feedback, I added JsHtmlSanitizer .
https://code.google.com/p/google-caja/wiki/JsHtmlSanitizer

**Comment by jamesa** [comment]
@idoco Thanks for fixing this! By the way, can you point me in the right direction to getting this running on my machine? Specifically about this: https://github.com/idoco/map-chat/blob/gh-pages/javascript/main.js#L10 :)

**Comment by idoco** [comment]
Hi there @jamesa,
I fixed the main branch so it would be easier to run. There were several issues with instance specific values, like the maps api key and the server url. I think I fixed all of them so please fetch the changes and give it another try.
