### ISSUE TITLE
Allow translation

### ISSUE THREAD

**Issue by astronomersiva** [idoco/map-chat#31]
Adding a translate feature would make this a lot awesome.

**Comment by idoco** [comment]
That would be cool to have this as part of the app, but I didn't find an easy way to do it.

What I did find working for me is to use the builtin translation in chrome. For me it starts working when I add a # to the url line. It would be nice if you can find a more elegant way to do it :)

![chrome_translation](https://cloud.githubusercontent.com/assets/5776439/9301694/0fb22fc8-44d9-11e5-9c20-34bea35b136b.png)

**Comment by idoco** [comment]
I have added built-in google translation on the top right corner and I think the result is quite nice. 
This gives the app a new Babel fish like spin, and It took just 6 lines to embed it! :)

![trans1](https://cloud.githubusercontent.com/assets/5776439/9579581/75709d8a-4ffc-11e5-9b7b-6b0a783b69ea.png)

![trans2](https://cloud.githubusercontent.com/assets/5776439/9579583/77ecd268-4ffc-11e5-99f1-6cad1a6f0274.png)
