### ISSUE TITLE
Rework blacklisting

### ISSUE THREAD

**Issue by trevorsenior** [idoco/map-chat#32]
@idoco -- Would you be open to a PR that adjusts how the current blacklist functions? I've been blacklisted after quickly editing a message (under the [500ms current limit](https://github.com/idoco/map-chat/blob/master/server/ChatVerticle.java#L93)) using a modified client to remove the need to click on the chat box to send a message.

My initial thoughts:

The current system only checks the timestamp of the last message vs. the current message. It would be nice to support an average timestamp of the last 10 messages (or so). If the average message span between those 10 messages is under 500 ms _then_ blacklist the user.

It should be a quick fix (even if I don't know Java all that well), but just wanted some feedback before I get started on it. Thanks.

**Comment by idoco** [comment]
Yes! I agree that the current system is too strict. I Also had plans to change it to be IP based and not session id based which will help to block users using multiple sessions for "sky writing". 

I would be happy to help if you feel like implementing something better. Please take into consideration that I still want to keep the code as minimal, clean and elegant as possible, so I might be slightly nagging about it :)

**Comment by trevorsenior** [comment]
Awesome I'll start work on it later. I'd appreciate any feedback on my rusty Java skills so nit pick away at the PR I open. :wink:
