### ISSUE TITLE
connection lost, please refresh :(

### ISSUE THREAD

**Issue by kapigsaan** [idoco/map-chat#39]
http://128.199.130.99/map-chat/

 in here.. I don't know what i did wrong.. ??..

vertx run ChatVerticle.java
Succeeded in deploying verticle

![screenshot from 2016-08-18 15 06 18](https://cloud.githubusercontent.com/assets/16680149/17765017/cb9aa7f4-6555-11e6-9cd2-f633960345bb.png)

**Comment by idoco** [comment]
Since I had many problems with malicious users trying to attack map-chat server, I've added this [line](https://github.com/idoco/map-chat/blob/master/server/ChatVerticle.java#L59) which blocks all connecting from non allowed origin. As default only `localhost` is allowed (http://128.199.130.99 for example will be blocked). To fix this just remove the ```&& origin.startsWith("http://localhost") ``` clause or change it to your domain.

Since it is not very intuitive, maybe I should remove this line from the master branch and leave it only in the gh-pages one.

**Comment by kapigsaan** [comment]
i just change it as you said... but still,  don't work.. 

![screenshot from 2016-08-18 15 29 20](https://cloud.githubusercontent.com/assets/16680149/17765521/eba5808e-6558-11e6-9053-51fe5d4b76f8.png)


or is there someting im missing? 

![screenshot from 2016-08-18 15 34 55](https://cloud.githubusercontent.com/assets/16680149/17765609/7ef2916a-6559-11e6-89bc-680a5b28b5ea.png)

**Comment by idoco** [comment]
Yes, I see that you main.js file is still trying to connect to localhost:8080 
![mapchat_error](https://cloud.githubusercontent.com/assets/5776439/17765729/53da753e-6530-11e6-888f-9edd94253d70.png)

**Comment by idoco** [comment]
It looks like you've change it to `http://chatmap.cloudapp.net/chat" that is my demo server which will block connections from your page. You should change it to the host/ip running your vertx server

**Comment by kapigsaan** [comment]
oh.. okay ^_^ ..

**Comment by kapigsaan** [comment]
uhmm.. still same .. 

and now js error
 .. Connection lost, scheduling reconnect

**Comment by idoco** [comment]
Did you try it with `http://128.199.130.99:8080/chat`? the vertx server is listening on 8080.

**Comment by kapigsaan** [comment]
thank you!... ^_^

**Comment by idoco** [comment]
Glad to hear that it is now working for you :)

**Comment by kapigsaan** [comment]
yeah... ^_^

 .. by the way.. can i Use it in my Project? ..

 .. but i will be removing the fork me in gitlab part?..

**Comment by idoco** [comment]
Yeah, you can remove the fork me banner, but please keep some link to the original project.

**Comment by kapigsaan** [comment]
oh okay... ^_^ thank you !!

**Comment by idoco** [comment]
By the way, you don't have maintain your own mapchat server for that, you can include it as an iframe in your page and make it link to a private chat map (i.e. http://idoco.github.io/map-chat/#kapigsaan-private-chat)

**Comment by kapigsaan** [comment]
oh.. yeah i already did that..

 128.199.130.99/chat

haha.. but i just want to customize it a little bit. thats why ^_^ ....

 by the way can i modify it a bit?

**Comment by idoco** [comment]
Feel free to change anything you want, just please leave a link to the original project :+1:

**Comment by kapigsaan** [comment]
yes of course  ^_^ .... ...  thank you again....

**Comment by ceokingxi** [comment]
How to deploy the codes to run the project?thank you!

**Comment by ceokingxi** [comment]
I have the same question,can you help me? Thanks.
