### ISSUE TITLE
Message Timestamp.

### ISSUE THREAD

**Issue by Rockdtben** [idoco/map-chat#5]
![image](https://cloud.githubusercontent.com/assets/1364938/8258113/f86bd042-1677-11e5-9998-a8b3db380337.png)

Maybe a timestamp there in a light blue text?

**Comment by idoco** [comment]
Since now messages are dismissed automatically after few seconds I think that message are not really needed. Right now any messaged you see is at most 15 seconds old. I close this issue and might reopen it in the future if the conditions change.
