### ISSUE TITLE
Allow messages to fade away using a ttl

### ISSUE THREAD

**Issue by ataki** [idoco/map-chat#6]
Too many messages are cropping up in the same location. Have the callouts fade away after a while. Would also give off the feeling of realtime.

![screen shot 2015-06-19 at 10 02 39 am](https://cloud.githubusercontent.com/assets/728509/8258531/7efec44c-166a-11e5-8b1c-e05a7cfd9dde.png)

**Comment by Rockdtben** [comment]
#11

**Comment by ataki** [comment]
Awesome! Closing and will refer to the PR
